# Generated by Django 3.2 on 2022-11-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
